baseURL = "https://ash-z01.github.io/"
languageCode = "en-us"
title = "XYZ Cell Space"
theme = "kagome"

# canonifyurls = true
paginate = 7  # 12
hasCJKLanguage = true
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."


# 作者信息
[author]
  name = "ash"
  email = "ash-z@foxmail.com"
  description = "What I cannot create, I do not understand~"
  # avatar = "https://s.gravatar.com/avatar/7b5a0b07a98895278cfa862b1f32ae8f?s=200&r=g&d=retro"
  avatar = "/images/OnionKnight.jpg"

[menu]
  # 顶部导航栏
  [[menu.main]]
    identifier = "/"
    name = "HOME"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "/posts"
    name = "POSTS"
    url = "/posts"
    weight = 2
  [[menu.main]]
    identifier = "/message"
    name = "MESSAGE"
    url = "/message"
    weight = 3
  [[menu.main]]
    identifier = "/link"
    name = "LINK"
    url = "/link"
    weight = 4
  [[menu.main]]
    identifier = "/about"
    name = "ABOUT"
    url = "/about"
    weight = 3
  
  # 底部社交图标
  [[menu.social]]
    identifier = "github"
    name = "github"
    url = "https://github.com/ash-z01"
    weight = 1
  # [[menu.social]]
  #   identifier = "twitter"
  #   name = "twitter"
  #   url = "https://twitter.com/guanquanhong"
  #   weight = 2
  # [[menu.social]]
  #   identifier = "instagram"
  #   name = "instagram"
  #   url = "https://www.instagram.com/sukoshi_dayo/"
  #   weight = 3
  # [[menu.social]]
  #   identifier = "weibo"
  #   name = "weibo"
  #   url = "https://weibo.com/u/5561168966"
  #   weight = 4
  # [[menu.social]]
  #   identifier = "zhihu"
  #   name = "zhihu"
  #   url = "https://www.zhihu.com/people/miku-84"
  #   weight = 5

# URL格式
[permalinks]
  posts = "/:section/:year:month:day:15:04/"
  files = "/:section/:year:month:day:15:04/"
  docs = "/:section/:year:month:day:15:04/"

# 主题相关配置项
[params]
  keywords = ['theme', 'kagome']
  description = ""
  mainSections = ["posts"]
  # 国内备案号
  beian = ""
  # TOC目录出现字符长度限制
  toc_show_len = 300

  [params.widget]
    # 相关文章推荐数量
    articles_count = 6
    # 分类相关显示数量
    categories_count = 6
    # 标签相关显示数量
    tags_count = 12

  [params.aplayer]
    theme = "#b7daff"
    autoplay = false
    loop = "none"
    mutex = true

  [params.dplayer]
    theme = "#b7daff"
    autoplay = false
    loop = false
    mutex = true
